# Generated by Django 4.1.2 on 2023-07-16 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('currency', models.CharField(max_length=50)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomBusinessUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('business_bio', models.TextField(blank=True, max_length=1350, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=main.models.CustomBusinessUser.dynamic_upload)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to=main.models.CustomBusinessUser.dynamic_upload)),
                ('business_slug', models.SlugField(blank=True, null=True)),
                ('stripe_id', models.CharField(blank=True, max_length=200, null=True)),
                ('pref_tz', models.CharField(default='UTC', max_length=255)),
                ('password_reset_date', models.DateTimeField(blank=True, null=True)),
                ('password_reset_code', models.TextField(blank=True, null=True)),
                ('business_accept', models.BooleanField(blank=True, default=False, null=True, verbose_name='Business accepted terms and conditions and privacy policy')),
                ('services', models.ManyToManyField(blank=True, to='main.service')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.DateTimeField()),
                ('address', models.TextField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_booked', models.BooleanField(default=False)),
                ('stripe_id', models.CharField(blank=True, max_length=255, null=True)),
                ('charge_id', models.CharField(blank=True, max_length=255, null=True)),
                ('refunded', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('service_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('price_reference', models.IntegerField(blank=True, null=True)),
                ('currency_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('client_accept', models.BooleanField(blank=True, default=False, null=True, verbose_name='Client accepted terms and conditions and privacy policy')),
                ('verification_code', models.TextField(blank=True, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to=main.models.Appointment.dynamic_upload)),
                ('verified', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.service')),
            ],
        ),
    ]
