# Generated by Django 4.1.2 on 2023-07-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombusinessuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
