# Generated by Django 4.1.2 on 2023-07-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_custombusinessuser_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombusinessuser',
            name='email_auth_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
