# Generated by Django 4.1.2 on 2023-07-23 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_custombusinessuser_email_auth_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custombusinessuser',
            name='email_auth_code',
        ),
    ]
